version: '3.8'

services:
  # データサーバー（PostgreSQL）の設定
  db:
    image: postgres:16
    container_name: namako_db
    restart: always
    environment:
      POSTGRES_USER: namako_user
      POSTGRES_PASSWORD: namako_password
      POSTGRES_DB: namako_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
